name: Deploy

on:
  push:
    branches:
      - gh-actions
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    name: Terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Plan
        run: terraform plan -out main.tfplan
        working-directory: ./Deploy
    