name: Deploy

on:
  push:
    branches:
      - gh-actions
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    name: Terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_APP_ID }}","clientSecret":"${{ secrets.ARM_APP_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION }}","tenantId":"${{ secrets.ARM_TENANT }}"}'
          enable-AzPSSession: true 

      - name: Run Azure PowerShell Script File
        uses: azure/powershell@v1
        with:
          inlineScript: ./Deploy/CreateTfStateStorageAccount.ps1
          azPSVersion: "latest"
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./Deploy

      - name: Terraform Plan
        run: terraform plan -out main.tfplan
        working-directory: ./Deploy
        env:
          TF_VAR_appId: ${{ secrets.ARM_APP_ID }}
          TF_VAR_password: ${{ secrets.ARM_APP_SECRET }}
          TF_VAR_tenant: ${{ secrets.ARM_TENANT }}
          TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION }}

      - name: Terraform Apply
        run: terraform apply main.tfplan
        working-directory: ./Deploy
        env:
          TF_VAR_appId: ${{ secrets.ARM_APP_ID }}
          TF_VAR_password: ${{ secrets.ARM_APP_SECRET }}
          TF_VAR_tenant: ${{ secrets.ARM_TENANT }}
          TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION }}




          
    