name: Deploy

on:
  push:
    branches:
      - gh-actions
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    name: Terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./Deploy
        env:
          ARM_ACCESS_KEY: ${{ secrets.BACKEND_ACCESS_KEY }}

      - name: Terraform Plan
        run: terraform plan -out main.tfplan
        working-directory: ./Deploy
        env:
          ARM_ACCESS_KEY: ${{ secrets.BACKEND_ACCESS_KEY }}
          TF_VAR_appId: ${{ secrets.ARM_APP_ID }}
          TF_VAR_password: ${{ secrets.ARM_APP_SECRET }}
          TF_VAR_tenant: ${{ secrets.ARM_TENANT }}
          TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION }}

      - name: Terraform Apply
        run: terraform apply main.tfplan
        working-directory: ./Deploy
        env:
          ARM_ACCESS_KEY: ${{ secrets.BACKEND_ACCESS_KEY }}
          TF_VAR_appId: ${{ secrets.ARM_APP_ID }}
          TF_VAR_password: ${{ secrets.ARM_APP_SECRET }}
          TF_VAR_tenant: ${{ secrets.ARM_TENANT }}
          TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION }}




          
    